name: cd_pr_close_release
on:
  push:
    branches:
      - develop
jobs:
  merge-develop-to-main:
    if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check commit message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $commit_message == *"release: "*([0-9]).*([0-9]).*([0-9]) ]]; then
            echo "Valid commit message, merging to main."
            git checkout main
            git pull origin main
            git merge --no-ff develop
            git push origin main
          else
            echo "Invalid commit message, not merging."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
