name: Format and Lint Code
on:
  push:
    branches:
      - main
      - develop
jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,md} --print-width 100  --single-quote --quote-props preserve --no-bracket-spacing --arrow-parens avoid --embedded-language-formatting off
          only_changed: True
          commit_message: 'style: format code'
