name: ci_pr_format_test
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,md} --print-width 100  --single-quote --quote-props preserve --no-bracket-spacing --arrow-parens avoid --embedded-language-formatting off
          only_changed: True
          commit_message: 'style: format code'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.1]
    env:
      CYPRESS_email: ${{secrets.CYPRESS_EMAIL}}
      CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
      CYPRESS_baseurl: http://dev.app.portapporta.webmapp.it
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: 'baseurl=http://dev.app.portapporta.webmapp.it'
          browser: chrome

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
