name: ci_pr_style_test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.1]
    env:
      CYPRESS_email: ${{secrets.CYPRESS_EMAIL}}
      CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
      CYPRESS_baseurl: http://dev.app.portapporta.webmapp.it

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{ts,md} --print-width 100  --single-quote true --quote-props preserve --no-bracket-spacing true --arrow-parens avoid --embedded-language-formatting off
          only_changed: True
          commit_message: 'style: format code'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: 'baseurl=http://dev.app.portapporta.webmapp.it'
          browser: chrome

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
