name: ci_pr_format_test
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    uses: webmappsrl/pap/.github/workflows/job_format.yml@develop
  test:
    uses: webmappsrl/pap/.github/workflows/job_test.yml@develop
    secrets: inherit
