# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci_test_deploy_dev

on:
  push:
    branches: [develop]
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.1]
    env:
      CYPRESS_email: ${{secrets.CYPRESS_EMAIL}}
      CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
      CYPRESS_baseurl: http://dev.app.portapporta.webmapp.it
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_email: ${{secrets.CYPRESS_EMAIL}}
          CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
          CYPRESS_baseurl: http://dev.app.portapporta.webmapp.it
        with:
          config: baseurl=http://dev.app.portapporta.webmapp.it
          browser: chrome
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: 'cd pap && ./scripts/dev_deploy.sh'
