name: job_test
on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
jobs:
  deploy-dev:
    name: deploy on surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Domain Name
        id: domain
        run: |
          if [ "${{ inputs.branch_name }}" == "develop" ]; then
            DOMAIN_NAME="dev.pap.surge.sh"
          else
            BRANCH_NAME=$(echo ${{ inputs.branch_name }} | sed -e "s/[^a-zA-Z0-9]/-/g")
            DOMAIN_NAME="${BRANCH_NAME:0:4}.pap.surge.sh"
          fi
          echo "::set-output name=DOMAIN_NAME::$DOMAIN_NAME"
        shell: bash
      - name: Extract ID from commit message or use default
        id: deploy_id
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          ID=$(echo $COMMIT_MESSAGE | grep -oP '(?<=--id )\d+') || echo "ID not found in commit message, using default."
          if [ -z "$ID" ]; then
            ID=4
          fi
          echo "::set-output name=DEPLOY_ID::$ID"
        shell: bash
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Sostituisci con la versione di Node.js che usi
          cache: 'npm'
      - name: Create .env file
        run: |
          echo EMAIL = ${{ secrets.PAP_EMAIL }} >> .env
          echo PASSWORD = ${{ secrets.PAP_PASSWORD }} >> .env
      - name: Create theme directory
        run: |
          mkdir -p projects/pap/src/theme
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
      - run: npm install
      - name: Run Gulp  ${{ env.DOMAIN_URL }}
        env:
          EMAIL: ${{ secrets.PAP_EMAIL }}
          PASSWORD: ${{ secrets.PAP_PASSWORD }}
        run: npx gulp surge-deploy --id ${{ env.DEPLOY_ID }}
      - name: Deploy to  ${{ env.DOMAIN_URL }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ env.DOMAIN_URL }}
          project: 'dist/pap'
          login: ${{ secrets.SURGE_EMAIL }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Display Domain Name
        run: echo "DOMAIN_NAME=${{ env.DOMAIN_URL }}"
  test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_baseurl: ${{env.DOMAIN_URL}}
          CYPRESS_email: ${{secrets.CYPRESS_EMAIL}}
          CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
        with:
          browser: chrome

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
