name: Make a release

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/release-please-action
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          pull-request-title-pattern: 'release: ${version}'
          pull-request-header: ':robot: I have created a release. Changelog updated with this data:'
