name: Merge develop to main on tag push

on:
  push:
    tags:
      - 'v*'

jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge develop to main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
